# This config+template creates a Cloud build trigger for every CFT DM template
# by crawling through the repository. For this crawl we use glob import which
# needs to be enabled:
#
# gcloud config set deployment_manager/glob_imports True
#
# Currently the repo is hardcoded.

imports:
  - path: cft-triggers.py
    name: cft-triggers.py
  - path: ../../templates/**/*.md

resources:
  - name: cft-triggers
    type: cft-triggers.py
    properties:
      description: CFT-DM-#template# PR trigger
      github:
        name: cloud-foundation-toolkit
        owner: GoogleCloudPlatform
        pullRequest:
          branch: cft-dm-dev
      filename: dm/CI/cft_test_runner/cloudbuild-test.yaml
      substitutions:
        _BATS_TEST_FILE: ./templates/#template#/tests/integration/#template#.bats
      includedFiles:
        - dm/templates/#template#
        - dm/templates/#template#/*.py
        - dm/templates/#template#/*.schema
        - dm/templates/#template#/tests/integration/*