version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    groups:
      all:
        patterns:
        - "*"
  - package-ecosystem: "gomod"
    directory: /cli
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      all:
        patterns:
        - "*"
  - package-ecosystem: "gomod"
    directory: /infra/blueprint-test
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      all:
        patterns:
        - "*"
  - package-ecosystem: "gomod"
    directory: /infra/module-swapper
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      all:
        patterns:
        - "*"
  - package-ecosystem: "gomod"
    directory: /infra/utils/fbf
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      all:
        patterns:
        - "*"
