resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  webhook_token: ((forseti.github_webhook_token))
  source:
    repository: forseti-security/terraform-google-forseti
    access_token: ((github.pr-access-token))

- name: lint-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/lint
    tag: 2.4.0
    username: _json_key
    password: ((sa.google))

- name: integration-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/kitchen-terraform
    tag: 2.3.0
    username: _json_key
    password: ((sa.google))

jobs:

- name: lint-tests
  public: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-lint-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: pending
  - get: lint-test-image
    trigger: true
  - task: run
    image: lint-test-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: terraform-google-forseti
      - name: lint-test-image
      run:
        path: make
        args:
          - '-s'
          - check
        dir: terraform-google-forseti
  on_success:
    put: notify-lint-test-success
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: success
  on_failure:
    put: notify-lint-test-failure
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: failure
  on_abort:
    put: notify-lint-test-error
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: error

- name: integration-tests
  max_in_flight: 3
  public: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-integration-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: pending
  - get: integration-test-image
    trigger: true
  - aggregate:

    - task: run-tests-simple-example
      image: integration-test-image
      file: pull-request/test/ci/simple-example.yml
      params: &run-tests-params
        PROJECT_ID: ((forseti.phoogle_project_id))
        ORG_ID: ((phoogle.org_id))
        DOMAIN: ((phoogle.domain))
        GSUITE_ADMIN_EMAIL: ((phoogle.admin_account_email))
        SERVICE_ACCOUNT_JSON: ((forseti.phoogle_sa))
        NETWORK_PROJECT: ((forseti.phoogle_network_project))
        NETWORK: ((forseti.phoogle_network))
        REGION: ((forseti.phoogle_region))
        SUBNETWORK: ((forseti.phoogle_subnetwork))
        ENFORCER_PROJECT: ((forseti.phoogle_enforcer_project))

    - task: run-tests-shared-vpc
      image: integration-test-image
      file: pull-request/test/ci/shared-vpc.yml
      params:
        <<: *run-tests-params

    - task: run-tests-real-time-enforcer
      image: integration-test-image
      file: pull-request/test/ci/real-time-enforcer.yml
      params:
        <<: *run-tests-params

    - task: run-tests-real-time-enforcer-roles
      image: integration-test-image
      file: pull-request/test/ci/real-time-enforcer-roles.yml
      params:
        <<: *run-tests-params

    - task: run-tests-real-time-enforcer-sinks
      image: integration-test-image
      file: pull-request/test/ci/real-time-enforcer-sinks.yml
      params:
        <<: *run-tests-params

  on_success:
    put: notify-integration-test-success
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: success
  on_failure:
    put: notify-integration-test-failure
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: failure
  on_abort:
    put: notify-integration-test-error
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: error
