resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:

- name: pull-request
  type: pull-request
  webhook_token: ((project-factory.github_webhook_token))
  source:
    repository: terraform-google-modules/terraform-google-project-factory
    access_token: ((github.pr-access-token))

- name: lint-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/lint
    tag: 2.4.0
    username: _json_key
    password: ((sa.google))

- name: unit-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/unit
    username: _json_key
    password: ((sa.google))

- name: integration-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/kitchen-terraform
    tag: 2.0.0
    username: _json_key
    password: ((sa.google))

jobs:

- name: lint-tests
  public: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-lint-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: pending
  - get: lint-test-image
    trigger: true
  - task: run
    image: lint-test-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: terraform-google-project-factory
      run:
        path: make
        args:
        - '-s'
        - check
        dir: terraform-google-project-factory
  on_success:
    put: notify-lint-test-success
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: success
  on_failure:
    put: notify-lint-test-failure
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: failure
  on_abort:
    put: notify-lint-test-error
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: error

- name: unit-tests
  public: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-unit-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: unit-tests
      status: pending
  - get: unit-test-image
    trigger: true
  - task: run
    image: unit-test-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: terraform-google-project-factory
      run:
        path: make
        args: ['test_unit']
        dir: terraform-google-project-factory
  on_success:
    put: notify-unit-test-success
    resource: pull-request
    params:
      path: pull-request
      context: unit-tests
      status: success
  on_failure:
    put: notify-unit-test-failure
    resource: pull-request
    params:
      path: pull-request
      context: unit-tests
      status: failure
  on_abort:
    put: notify-unit-test-error
    resource: pull-request
    params:
      path: pull-request
      context: unit-tests
      status: error

- name: integration-tests
  public: true
  serial: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-integration-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: pending
  - get: integration-test-image
    trigger: true
  - task: run-tests
    image: integration-test-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: terraform-google-project-factory
      run:
        path: make
        args: ['-s', 'test_integration']
        dir: terraform-google-project-factory
      params:
        ADMIN_ACCOUNT_EMAIL: ((phoogle.admin_account_email))
        BILLING_ACCOUNT_ID: ((phoogle.billing_account_id))
        DOMAIN: ((phoogle.domain))
        FOLDER_ID: ((project-factory.phoogle_folder_id))
        GROUP_NAME: ((phoogle.group_name))
        ORG_ID: ((phoogle.org_id))
        PROJECT_ID: ((project-factory.phoogle_project_id))
        SERVICE_ACCOUNT_JSON: ((project-factory.phoogle_sa))
  on_success:
    put: notify-lint-test-success
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: success
  on_failure:
    put: notify-integration-test-failure
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: failure
  on_abort:
    put: notify-integration-test-error
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: error
