resource_types:

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:

- name: pull-request
  type: pull-request
  webhook_token: ((cloud-nat.github_webhook_token))
  source:
    repository: terraform-google-modules/terraform-google-cloud-nat
    access_token: ((github.pr-access-token))

- name: lint-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/lint
    tag: 1.0.0
    username: _json_key
    password: ((sa.google))

- name: integration-test-image
  type: docker-image
  source:
    repository: gcr.io/cloud-foundation-cicd/cft/kitchen-terraform
    tag: 1.2.0
    username: _json_key
    password: ((sa.google))

jobs:

- name: lint-tests
  public: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-lint-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: pending
  - get: lint-test-image
    trigger: true
  - task: run
    image: lint-test-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: terraform-google-cloud-nat
      - name: lint-test-image
      run:
        path: make
        args:
          - '-s'
          - check
        dir: terraform-google-cloud-nat
  on_success:
    put: notify-lint-test-success
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: success
  on_failure:
    put: notify-lint-test-failure
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: failure
  on_abort:
    put: notify-lint-tests-abort
    resource: pull-request
    params:
      path: pull-request
      context: lint-tests
      status: error

- name: integration-tests
  public: true
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: notify-integration-test-pending
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: pending
  - get: integration-test-image
    trigger: true
  - task: run-tests
    image: integration-test-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: terraform-google-cloud-nat
      run:
        path: /bin/bash
        args:
        - ./test/run_ci.sh
        dir: terraform-google-cloud-nat
      params:
        PROJECT_ID: ((cloud-nat.phoogle_project_id))
        SERVICE_ACCOUNT_JSON: ((cloud-nat.phoogle_sa))
  on_success:
    put: notify-integration-tests-success
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: success
  on_failure:
    put: notify-integration-tests-failure
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: failure
  on_abort:
    put: notify-integration-tests-abort
    resource: pull-request
    params:
      path: pull-request
      context: integration-tests
      status: error
