resource_types:

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    webhook_token: ((iam.github_webhook_token))
    source:
      repository: terraform-google-modules/terraform-google-iam
      access_token: ((github.pr-access-token))

  - name: lint-test-image
    type: docker-image
    source:
      repository: gcr.io/cloud-foundation-cicd/cft/lint
      tag: 2.4.0
      username: _json_key
      password: ((sa.google))

  - name: integration-test-image
    type: docker-image
    source:
      repository: gcr.io/cloud-foundation-cicd/cft/kitchen-terraform
      tag: 2.2.0
      username: _json_key
      password: ((sa.google))

jobs:

  - name: lint-tests
    public: true
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: notify-lint-test-pending
        resource: pull-request
        params:
          path: pull-request
          context: lint-tests
          status: pending
      - get: lint-test-image
        trigger: true
      - task: run
        image: lint-test-image
        config:
          platform: linux
          inputs:
            - name: pull-request
              path: terraform-google-iam
            - name: lint-test-image
          run:
            path: make
            args:
              - '-s'
              - check
            dir: terraform-google-iam
    on_success:
      put: notify-lint-test-success
      resource: pull-request
      params:
        path: pull-request
        context: lint-tests
        status: success
    on_failure:
      put: notify-lint-test-failure
      resource: pull-request
      params:
        path: pull-request
        context: lint-tests
        status: failure
    on_abort:
      put: notify-lint-test-error
      resource: pull-request
      params:
        path: pull-request
        context: lint-tests
        status: error

  - name: integration-tests
    public: true
    plan:
      - get: pull-request
        trigger: true
        version: every
      - put: notify-integration-test-pending
        resource: pull-request
        params:
          path: pull-request
          context: integration-tests
          status: pending
      - get: integration-test-image
        trigger: true
      - task: run-tests
        image: integration-test-image
        config:
          platform: linux
          inputs:
            - name: pull-request
              path: terraform-google-iam
          run:
            path: make
            args:
              - '-s'
              - test_integration
            dir: terraform-google-iam
          params:
            FOLDER_ID: ((iam.phoogle_folder_id))
            PROJECT_ID: ((iam.phoogle_project_id))
            BILLING_ACCOUNT_ID: ((phoogle.billing_account_id))
            ORG_ID: ((phoogle.org_id))
            SERVICE_ACCOUNT_JSON: ((iam.phoogle_sa))
    on_success:
      put: notify-integration-test-success
      resource: pull-request
      params:
        path: pull-request
        context: integration-tests
        status: success
    on_failure:
      put: notify-integration-test-failure
      resource: pull-request
      params:
        path: pull-request
        context: integration-tests
        status: failure
    on_abort:
      put: notify-integration-test-error
      resource: pull-request
      params:
        path: pull-request
        context: integration-tests
        status: error
