apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ required "user is required!" .Values.database.user }}
spec:
  instanceRef:
    name: {{ required "instanceName is required!" .Values.database.instanceName }}
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: wordpress-cloudsql-db-credentials
        key: password
