apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: sql-wp-sa-project-policymember
spec:
  member: serviceAccount:sql-wp-sa@{{ required "projectId is required!" .Values.google.projectId }}.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    kind: Project
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: {{ required "projectId is required!" .Values.google.projectId }}
