apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-wp-ksa-wi
  annotations:
    iam.gke.io/gcp-service-account: sql-wp-sa@{{ required "projectId is required!" .Values.google.projectId }}.iam.gserviceaccount.com
