apiVersion: v1
kind: Secret
metadata:
  name: wordpress-cloudsql-db-credentials
stringData:
  projectId: {{ required "projectId is required!" .Values.google.projectId }}
  username: {{ required "user is required!" .Values.database.user }}
  password: {{ required "password is required!" .Values.database.password }}
  connectionName: {{ required "region is required!" .Values.google.region }}:{{ required "instanceName is required!" .Values.database.instanceName }}
