apiVersion: v1
kind: Service
metadata:
  name: wordpress-external
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
