# find . -name "*.yam"l | grep examples| sort -n | awk '{print "- name: 'gcr.io/\$PROJECT_ID/cft-schema'\n  args: [`"$1"`]"}' | sed "s/\`/'/g"

steps:
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/autoscaler/examples/autoscaler_regional.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/autoscaler/examples/autoscaler_zonal.yaml']
# bug 
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/backend_service/examples/backend_service_global.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/backend_service/examples/backend_service_regional.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/bastion/examples/bastion.yaml']
# Skip, complex example
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/bigquery/examples/bigquery.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloudbuild/examples/cloudbuild_reposource.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloudbuild/examples/cloudbuild_storagesource.yaml']
# FAILING
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/cloudbuild/examples/cloudbuild_trigger.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloudbuild/examples/cloudbuild.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_function/examples/cloud_function_upload.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_function/examples/cloud_function.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_router/examples/cloud_router.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_spanner/examples/cloud_spanner.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_sql/examples/cloud_sql_read_replica.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_sql/examples/cloud_sql.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_tasks/examples/cloud_tasks_queue.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/cloud_tasks/examples/cloud_tasks_task.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/dataproc/examples/dataproc.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/dns_managed_zone/examples/dns_managed_zone_legacy.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/dns_managed_zone/examples/dns_managed_zone_private_visibility_config.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/dns_managed_zone/examples/dns_managed_zone_private.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/dns_managed_zone/examples/dns_managed_zone_public.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/dns_managed_zone/examples/dns_managed_zone.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/dns_records/examples/dns_records.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/external_load_balancer/examples/external_load_balancer_https.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/external_load_balancer/examples/external_load_balancer_http.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/external_load_balancer/examples/external_load_balancer_ssl.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/external_load_balancer/examples/external_load_balancer_tcp.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/firewall/examples/firewall.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/folder/examples/folder.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/forseti/examples/forseti.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/forwarding_rule/examples/forwarding_rule_global.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/forwarding_rule/examples/forwarding_rule_regional.yaml']
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/gcs_bucket/examples/gcs_bucket_iam_bindings.yaml']
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/gcs_bucket/examples/gcs_bucket_lifecycle.yaml']
# SCHEMA version issue
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/gcs_bucket/examples/gcs_bucket.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/gke/examples/gke_regional_private.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/gke/examples/gke_regional.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/gke/examples/gke_zonal.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/haproxy/examples/haproxy.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/healthcheck/examples/healthcheck.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/iam_custom_role/examples/iam_custom_role.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/iam_member/examples/iam_member.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/instance/examples/instance.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/instance_template/examples/instance_template.yaml']
# Schema faulty?
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/interconnect_attachment/examples/interconnect_attachment_dedicated.yaml']
# Schema faulty?
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/interconnect_attachment/examples/interconnect_attachment_partner.yaml']
# - name: gcr.io/$PROJECT_ID/cft-schema
# FIXME
#   args: ['./templates/interconnect/examples/interconnect_dedicated.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/internal_load_balancer/examples/internal_load_balancer.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/ip_reservation/examples/ip_reservation.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/kms/examples/kms_signkey.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/kms/examples/kms.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/logsink/examples/billingaccount_logsink_bucket_destination.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/logsink/examples/folder_logsink_bq_destination.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/logsink/examples/org_logsink_pubsub_destination.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/logsink/examples/project_logsink_bucket_destination.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/managed_instance_group/examples/managed_instance_group_healthcheck.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/managed_instance_group/examples/managed_instance_group.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/nat_gateway/examples/nat_gateway.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/network/examples/network.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/network_peering/examples/network_peering.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/org_policy/examples/org_policy.yaml']
# FIXME
# - name: gcr.io/$PROJECT_ID/cft-schema
#   args: ['./templates/project/examples/project.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/pubsub/examples/pubsub_push.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/pubsub/examples/pubsub.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/route/examples/route.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/runtime_config/examples/runtime_config.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/shared_vpc_subnet_iam/examples/shared_vpc_subnet_iam_bindings.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/shared_vpc_subnet_iam/examples/shared_vpc_subnet_iam_legacy.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/shared_vpc_subnet_iam/examples/shared_vpc_subnet_iam_policy.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/ssl_certificate/examples/ssl_certificate.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/stackdriver_metric_descriptor/examples/stackdriver_metric_descriptor.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/target_proxy/examples/target_proxy_https.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/target_proxy/examples/target_proxy_http.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/target_proxy/examples/target_proxy_ssl.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/target_proxy/examples/target_proxy_tcp.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/url_map/examples/url_map.yaml']
- name: gcr.io/$PROJECT_ID/cft-schema
  args: ['./templates/vpn/examples/vpn.yaml']
tags: ['cft-dm-schema-runner']
