name: 'Feature request'
description: 'File a feature request'
labels: ['enhancement']
body:
- type: 'markdown'
  attributes:
    value: |-
      Thank you for requesting a feature. Please complete the form below so we can triage and prioritize your feature.

- id: 'component'
  type: 'textarea'
  attributes:
    label: 'Component'
    description: 'Which component is this FR for? Examples: CLI, Devtools, Linter, Test framework etc'
    render: 'markdown'

- id: 'tldr'
  type: 'textarea'
  attributes:
    label: 'TL;DR'
    description: 'Describe the feature in 1-2 sentences.'
  validations:
    required: true

- id: 'detailed_design'
  type: 'textarea'
  attributes:
    label: 'Detailed design'
    description: 'Do you have more information about a detailed design? Are there specific considerations to take? Include sample configuration if possible.'
    render: 'markdown'

- id: 'additional'
  type: 'textarea'
  attributes:
    label: 'Additional information'
    description: 'Is there anything else you think we should know?'
