# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mysql-ha-solution # {"$ref":"#/definitions/io.k8s.cli.setters.instance-name"}
  labels:
    solution: mysql-ha
    node: master
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    activationPolicy: ALWAYS
    diskAutoresize: true
    diskSize: 10
    diskType: PD_SSD
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-n1-standard-1
    backupConfiguration:
      binaryLogEnabled: true
      enabled: true
      startTime: 20:55
    databaseFlags:
    - name: long_query_time
      value: "1"
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: true
      authorizedNetworks:
      - name: mysql-ha-solution-cidr
        value: 192.10.10.10/32
    locationPreference:
      zone: us-central1-c
    maintenanceWindow:
      day: 7
      hour: 12
      updateTrack: stable
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mysql-ha-solution-failover-test # {"$ref":"#/definitions/io.k8s.cli.substitutions.failover-instance-name"}
  labels:
    solution: mysql-ha
    node: failover
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  masterInstanceRef:
    name: mysql-ha-solution # {"$ref":"#/definitions/io.k8s.cli.setters.instance-name"}
  replicaConfiguration:
    connectRetryInterval: 5
  settings:
    activationPolicy: ALWAYS
    crashSafeReplication: true
    diskAutoresize: true
    diskSize: 10
    diskType: PD_SSD
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-n1-standard-1
    databaseFlags:
    - name: long_query_time
      value: "1"
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: false
      authorizedNetworks:
      - name: mysql-ha-solution-cidr
        value: 192.10.10.10/32
    locationPreference:
      zone: us-central1-a
    maintenanceWindow:
      day: 3
      hour: 20
      updateTrack: canary
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mysql-ha-solution-replica-test0 # {"$ref":"#/definitions/io.k8s.cli.substitutions.replica-instance-0-name"}
  labels:
    solution: mysql-ha
    node: replica-test0
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  masterInstanceRef:
    name: mysql-ha-solution # {"$ref":"#/definitions/io.k8s.cli.setters.instance-name"}
  replicaConfiguration:
    connectRetryInterval: 5
  settings:
    activationPolicy: ALWAYS
    crashSafeReplication: true
    diskAutoresize: true
    diskSize: 10
    diskType: PD_HDD
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-n1-standard-1
    databaseFlags:
    - name: long_query_time
      value: "1"
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: false
      authorizedNetworks:
      - name: mysql-ha-solution-cidr
        value: 192.10.10.10/32
    locationPreference:
      zone: us-central1-a
    maintenanceWindow:
      day: 1
      hour: 22
      updateTrack: stable
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mysql-ha-solution-replica-test1 # {"$ref":"#/definitions/io.k8s.cli.substitutions.replica-instance-1-name"}
  labels:
    solution: mysql-ha
    node: replica-test1
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  masterInstanceRef:
    name: mysql-ha-solution # {"$ref":"#/definitions/io.k8s.cli.setters.instance-name"}
  replicaConfiguration:
    connectRetryInterval: 5
  settings:
    activationPolicy: ALWAYS
    crashSafeReplication: true
    diskAutoresize: true
    diskSize: 10
    diskType: PD_HDD
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-n1-standard-1
    databaseFlags:
    - name: long_query_time
      value: "1"
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: false
      authorizedNetworks:
      - name: mysql-ha-solution-cidr
        value: 192.10.10.10/32
    locationPreference:
      zone: us-central1-b
    maintenanceWindow:
      day: 1
      hour: 22
      updateTrack: stable
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mysql-ha-solution-replica-test2 # {"$ref":"#/definitions/io.k8s.cli.substitutions.replica-instance-2-name"}
  labels:
    solution: mysql-ha
    node: replica-test2
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  masterInstanceRef:
    name: mysql-ha-solution # {"$ref":"#/definitions/io.k8s.cli.setters.instance-name"}
  replicaConfiguration:
    connectRetryInterval: 5
  settings:
    activationPolicy: ALWAYS
    crashSafeReplication: true
    diskAutoresize: true
    diskSize: 10
    diskType: PD_HDD
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-n1-standard-1
    databaseFlags:
    - name: long_query_time
      value: "1"
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: false
      authorizedNetworks:
      - name: mysql-ha-solution-cidr
        value: 192.10.10.10/32
    locationPreference:
      zone: us-central1-c
    maintenanceWindow:
      day: 1
      hour: 22
      updateTrack: stable
