# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: mysql-private-database # {"$ref":"#/definitions/io.k8s.cli.setters.database-name"}
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: mysql-private-instance # {"$ref":"#/definitions/io.k8s.cli.setters.instance-name"}
