#!/bin/bash
#
# Copyright 2018 Google Inc. All Rights Reserved.
#

# Finds the directory name for this script, and source the env
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "$DIR/cftenv"

# Executes cft
exec python -m "cloud_foundation_toolkit.cli" "$@"
