steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cft-ci-test:${_CFT_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/cft-ci-test',
        '--build-arg', 'CFT_VERSION=${_CFT_VERSION}',
        '.']
substitutions:
  _CFT_VERSION: 0.0.4

images:
- 'gcr.io/$PROJECT_ID/cft-ci-test:latest'
- 'gcr.io/$PROJECT_ID/cft-ci-test:$_CFT_VERSION'
tags: ['cft-test-dm']
