package bpmetadata

import (
	"sigs.k8s.io/kustomize/kyaml/yaml"
)

// BlueprintMetadata defines the overall structure for blueprint metadata.
type BlueprintMetadata struct {
	yaml.ResourceMeta `json:",inline" yaml:",inline"`
	Spec              BlueprintMetadataSpec `json:"spec" yaml:"spec"`
}

// BlueprintMetadataSpec defines the spec portion of the blueprint metadata.
// All immediate types within BlueprintMetadataSpec are inline and will
// not appear as nodes in metadata.
type BlueprintMetadataSpec struct {
	Info         BlueprintInfo         `json:"info,omitempty" yaml:"info,omitempty"`
	Content      BlueprintContent      `json:"content,omitempty" yaml:"content,omitempty"`
	Interfaces   BlueprintInterface    `json:"interfaces,omitempty" yaml:"interfaces,omitempty"`
	Requirements BlueprintRequirements `json:"requirements,omitempty" yaml:"requirements,omitempty"`
	UI           BlueprintUI           `json:"ui,omitempty" yaml:"ui,omitempty"`
}

type BlueprintInfo struct {
	// Title for the blueprint.
	// Autogenerated: First H1 text in readme.md.
	Title string `json:"title" yaml:"title"`

	// Blueprint source location and source type.
	// Autogen details in BlueprintRepoDetail.
	Source *BlueprintRepoDetail `json:"source" yaml:"source"`

	// Last released semantic version for the packaged blueprint.
	// Autogenerated: From the `module_name` attribute of the `provider_meta "google"` block.
	// E.g.
	// provider_meta "google" {
	//  module_name = "blueprints/terraform/terraform-google-log-analysis/v0.1.5"
	// }
	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	// Actuation tool e.g. Terraform and its required version.
	// Autogen details in BlueprintActuationTool.
	ActuationTool BlueprintActuationTool `json:"actuationTool,omitempty" yaml:"actuationTool,omitempty"`

	// Various types of descriptions associated with the blueprint.
	// Autogen details in BlueprintDescription.
	Description *BlueprintDescription `json:"description,omitempty" yaml:"description,omitempty"`

	// Path to an image representing the icon for the blueprint.
	// Will be set as "assets/icon.png", if present. Otherwise, it
	// can be manually authored.
	Icon string `json:"icon,omitempty" yaml:"icon,omitempty"`

	// The time estimate for configuring and deploying the blueprint.
	// Autogen details in BlueprintTimeEstimate.
	DeploymentDuration BlueprintTimeEstimate `json:"deploymentDuration,omitempty" yaml:"deploymentDuration,omitempty"`

	// The cost estimate for the blueprint based on preconfigured variables.
	// Autogen details in BlueprintCostEstimate.
	CostEstimate BlueprintCostEstimate `json:"costEstimate,omitempty" yaml:"costEstimate,omitempty"`

	// A list of GCP cloud products used in the blueprint.
	// Manually authored.
	CloudProducts []BlueprintCloudProduct `json:"cloudProducts,omitempty" yaml:"cloudProducts,omitempty"`

	// A configuration of fixed and dynamic GCP quotas that apply to the blueprint.
	// Manually authored.
	QuotaDetails []BlueprintQuotaDetail `json:"quotaDetails,omitempty" yaml:"quotaDetails,omitempty"`

	// Details on the author producing the blueprint.
	// Manually authored.
	Author BlueprintAuthor `json:"author,omitempty" yaml:"author,omitempty"`

	// Details on software installed as part of the blueprint.
	// Manually authored.
	SoftwareGroups []BlueprintSoftwareGroup `json:"softwareGroups,omitempty" yaml:"softwareGroups,omitempty"`

	// Support offered, if any for the blueprint.
	// Manually authored.
	SupportInfo BlueprintSupport `json:"supportInfo,omitempty" yaml:"supportInfo,omitempty"`
}

type BlueprintRepoDetail struct {
	// Autogenerated: URL from the .git dir.
	// Can be manually overridden with a custom URL if needed.
	Repo string `json:"repo" yaml:"repo"`

	// Set as "git" for now until more types are supported.
	SourceType string `json:"sourceType" yaml:"sourceType"`

	// optional directory location for a submodule
	Dir string `json:"dir,omitempty" yaml:"dir,omitempty"`
}

type BlueprintActuationTool struct {
	// Set as "Terraform" for now until more flavors are supported.
	Flavor string `json:"type,omitempty" yaml:"type,omitempty"`

	// Required version for the actuation tool.
	// Autogenerated: For Terraform this is the `required_version` set in
	// `terraform` block. E.g.
	// terraform {
	//   required_version = ">= 0.13"
	// }
	Version string `json:"version,omitempty" yaml:"version,omitempty"`
}

type BlueprintDescription struct {
	// Autogenerated: All types of descriptions are set with the markdown content
	// immediately after each type's heading declaration in readme.md.

	// Autogenerated: Markdown after "### Tagline".
	Tagline string `json:"tagline,omitempty" yaml:"tagline,omitempty"`

	// Autogenerated: Markdown after "### Detailed".
	Detailed string `json:"detailed,omitempty" yaml:"detailed,omitempty"`

	// Autogenerated: Markdown after "### PreDeploy".
	PreDeploy string `json:"preDeploy,omitempty" yaml:"preDeploy,omitempty"`

	// Autogenerated: Markdown after "### Html".
	HTML string `json:"html,omitempty" yaml:"html,omitempty"`

	// Autogenerated: Markdown after "### EulaUrls".
	EulaURLs []string `json:"eulaUrls,omitempty" yaml:"eulaUrls,omitempty"`

	// Autogenerated: Markdown after "### Architecture"
	// Deprecated. Use BlueprintContent.Architecture instead.
	Architecture []string `json:"architecture,omitempty" yaml:"architecture,omitempty"`
}

// A time estimate in secs required for configuring and deploying the blueprint.
type BlueprintTimeEstimate struct {
	// Autogenerated: Set using the content defined under "### DeploymentTime" E.g.
	// ### DeploymentTime
	// - Configuration: X secs
	// - Deployment: Y secs
	ConfigurationSecs int `json:"configuration,omitempty" yaml:"configuration,omitempty"`
	DeploymentSecs    int `json:"deployment,omitempty" yaml:"deployment,omitempty"`
}

// The cost estimate for the blueprint based on preconfigured variables.
type BlueprintCostEstimate struct {
	// Autogenerated: Set using the content defined under "### Cost" as a link
	// with a description E.g.
	// ### Cost
	// [View cost details](https://cloud.google.com/products/calculator?hl=en_US&_ga=2.1665458.-226505189.1675191136#id=02fb0c45-cc29-4567-8cc6-f72ac9024add)
	Description string `json:"description" yaml:"description"`
	URL         string `json:"url" yaml:"url"`
}

// A GCP cloud product used in the blueprint.
// Manually authored.
type BlueprintCloudProduct struct {
	// A top-level (e.g. "Compute Engine") or secondary (e.g. "Binary Authorization")
	// product used in the blueprint.
	ProductId string `json:"productId,omitempty" yaml:"productId,omitempty"`

	// Url for the product.
	PageURL string `json:"pageUrl" yaml:"pageUrl"`

	// A label string for the product, if it is not an integrated GCP product.
	// E.g. "Data Studio"
	Label string `json:"label,omitempty" yaml:"label,omitempty"`
}

type QuotaResourceType string

const (
	QuotaResTypeUndefined QuotaResourceType = "QUOTARESOURCETYPE_UNDEFINED"
	GCEInstance           QuotaResourceType = "GCE_INSTANCE"
	GCEDisk               QuotaResourceType = "GCE_DISK"
)

type QuotaType string

const (
	MachineType QuotaType = "MACHINE_TYPE"
	CPUs        QuotaType = "CPUs"
	DiskType    QuotaType = "DISK_TYPE"
	DiskSizeGB  QuotaType = "SIZE_GB"
)

type BlueprintQuotaDetail struct {
	// DynamicVariable, if provided, associates the provided input variable
	// with the corresponding resource and quota type. In its absence, the quota
	// detail is assumed to be fixed.
	DynamicVariable string `json:"variable,omitempty" yaml:"variable,omitempty"`

	// ResourceType is the type of resource the quota will be applied to i.e.
	// GCE Instance or Disk etc.
	ResourceType QuotaResourceType `json:"type" yaml:"type" jsonschema:"enum=GCE_INSTANCE,enum=GCE_DISK"`

	// QuotaType is a key/value pair of the actual quotas and their corresponding
	// values.
	QuotaType map[QuotaType]string `json:"quotaType" yaml:"quotaType"`
}

type BlueprintAuthor struct {
	// Name of template author or organization.
	Title string `json:"title" yaml:"title"`

	// Description of the author.
	Description string `json:"description,omitempty"  yaml:"description,omitempty"`

	// Link to the author's website.
	URL string `json:"url,omitempty" yaml:"url,omitempty"`
}

type SoftwareGroupType string

const (
	UnspecifiedSG SoftwareGroupType = "UNSPECIFIED"
	OS            SoftwareGroupType = "OS"
)

// A group of related software components for the blueprint.
type BlueprintSoftwareGroup struct {
	// Pre-defined software types.
	Type SoftwareGroupType `json:"type,omitempty" yaml:"type,omitempty" jsonschema:"enum=UNSPECIFIED,enum=OS"`

	// Software components belonging to this group.
	Software []BlueprintSoftware `json:"software,omitempty" yaml:"software,omitempty"`
}

// A description of a piece of a single software component
// installed by the blueprint.
type BlueprintSoftware struct {
	// User-visible title.
	Title string `json:"title" yaml:"title"`

	// Software version.
	Version string `json:"version,omitempty" yaml:"version,omitempty"`

	// Link to development site or marketing page for this software.
	URL string `json:"url,omitempty" yaml:"url,omitempty"`

	// Link to license page.
	LicenseURL string `json:"licenseUrl,omitempty" yaml:"licenseUrl,omitempty"`
}

// A description of a support option
type BlueprintSupport struct {
	//Description of the support option.
	Description string `json:"description" yaml:"description"`

	// Link to the page providing this support option.
	URL string `json:"url,omitempty" yaml:"url,omitempty"`

	// The organization or group that provides the support option (e.g.:
	// "Community", "Google").
	Entity string `json:"entity,omitempty" yaml:"entity,omitempty"`

	// Whether to show the customer's support ID.
	ShowSupportId bool `json:"showSupportId,omitempty" yaml:"showSupportId,omitempty"`
}

// BlueprintContent defines the detail for blueprint related content such as
// related documentation, diagrams, examples etc.
type BlueprintContent struct {
	// Diagrams are manually entered.
	Architecture  BlueprintArchitecture  `json:"architecture,omitempty" yaml:"architecture,omitempty"`
	Diagrams      []BlueprintDiagram     `json:"diagrams,omitempty" yaml:"diagrams,omitempty"`
	Documentation []BlueprintListContent `json:"documentation,omitempty" yaml:"documentation,omitempty"`
	SubBlueprints []BlueprintMiscContent `json:"subBlueprints,omitempty" yaml:"subBlueprints,omitempty"`
	Examples      []BlueprintMiscContent `json:"examples,omitempty" yaml:"examples,omitempty"`
}

// BlueprintInterface defines the input and output variables for the blueprint.
type BlueprintInterface struct {
	Variables []BlueprintVariable `json:"variables,omitempty" yaml:"variables,omitempty"`
	// VariableGroups are manually entered.
	VariableGroups []BlueprintVariableGroup `json:"variableGroups,omitempty" yaml:"variableGroups,omitempty"`
	Outputs        []BlueprintOutput        `json:"outputs,omitempty" yaml:"outputs,omitempty"`
}

// BlueprintRequirements defines the roles required and the associated services
// that need to be enabled to provision blueprint resources.
type BlueprintRequirements struct {
	Roles    []BlueprintRoles `json:"roles,omitempty" yaml:"roles,omitempty"`
	Services []string         `json:"services,omitempty" yaml:"services,omitempty"`
}

type BlueprintMiscContent struct {
	Name     string `json:"name" yaml:"name"`
	Location string `json:"location,omitempty" yaml:"location,omitempty"`
}

type BlueprintArchitecture struct {
	DiagramURL  string   `json:"diagram" yaml:"diagram"`
	Description []string `json:"description" yaml:"description"`
}

// BlueprintDiagram is manually entered.
type BlueprintDiagram struct {
	Name        string `json:"name" yaml:"name"`
	AltText     string `json:"altText,omitempty" yaml:"altText,omitempty"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

type BlueprintListContent struct {
	Title string `json:"title" yaml:"title"`
	URL   string `json:"url,omitempty" yaml:url,omitempty"`
}

type BlueprintVariable struct {
	Name        string      `json:"name,omitempty" yaml:"name,omitempty"`
	Description string      `json:"description,omitempty" yaml:"description,omitempty"`
	VarType     string      `json:"type,omitempty" yaml:"type,omitempty"`
	Default     interface{} `json:"default,omitempty" yaml:"default,omitempty"`
	Required    bool        `json:"required,omitempty" yaml:"required,omitempty"`
}

// BlueprintVariableGroup is manually entered.
type BlueprintVariableGroup struct {
	Name        string   `json:"name" yaml:"name"`
	Description string   `json:"description,omitempty" yaml:"description,omitempty"`
	Variables   []string `json:"variables,omitempty" yaml:"variables,omitempty"`
}

type BlueprintOutput struct {
	Name        string `json:"name" yaml:"name"`
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
}

type BlueprintRoles struct {
	Level string   `json:"level" yaml:"level"`
	Roles []string `json:"roles" yaml:"roles"`
}
