name: CFT CLI Tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'cli/**'
      - '.github/workflows/test-cli.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'cli/**'
      - '.github/workflows/test-cli.yml'

concurrency:
  group: '${{github.workflow}}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit:
    name: ${{ matrix.operating-system }} unit tests
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash
        working-directory: 'cli'
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: cli/go.mod
        cache-dependency-path: cli/go.sum
    - run: |-
        make test
