name: Test devtools image build
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "infra/build/**"
      - ".github/workflows/test-cft-devtools.yml"

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-dev-tools:
    name: Build CFT dev tools image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        run: |-
          cd infra/build && make build-image-developer-tools
