# Example of the Cloud Build trigger template usage.
#
# In this example, a Build trigger is created for the following Github repo.
# https://github.com/GoogleCloudBuild/gcbapp-example
#
# Pre-requisites steps for creating this trigger: 
# Step1: Login to github and fork the following github repo
#        https://github.com/GoogleCloudBuild/gcbapp-example
# Step2: Create a Cloud Source repo named gcbapp-example
#        After the repo is created successfully do the following     
#        - Select "Automatically mirror from Github/Bitbucket" option
#        - Select "Hosting Service", Choose "Github" from dropdown then Connect
#        - Follow steps to Authenticate your Github repo
#        - Once authenticated, select the repo (from Step1) from the list
#        - Select, "I consent .." checkbox then Click "connect"
#

imports:
  - path: templates/cloudbuild/trigger.py
    name: trigger.py

resources:
  - name: mybuildtrigger
    type: trigger.py
    properties:
      description: Cloud Build example app
      triggerTemplate:
        repoName: 'gcbapp-example'
        branchName: 'master'
      build:
        steps:
          - name: 'gcr.io/cloud-builders/docker'
            args:
              - 'build'
              - '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
              - '.'
          - name: 'gcr.io/cloud-builders/docker'
            args:
              - 'push'
              - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
        substitutions:
          _IMAGE_NAME: gcbapp-example
        images:
          - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'
