# Example of the DNS managed zone template usage.
#
# In this example, a private DNS managed zone is created with the use of
# the `visibility` and `privateVisibilityConfig` properties.

imports:
  - path: templates/dns_managed_zone/dns_managed_zone.py
    name: dns_managed_zone.py

resources:
  - name: private-mz-with-visibility
    type: dns_managed_zone.py
    properties:
      name: private-mz-with-visibility
      dnsName: private-visibility.local.
      description: "Private DNS Managed Zone with visibility config"
      visibility: private
      privateVisibilityConfig:
        kind: "dns#managedZonePrivateVisibilityConfig"
        networks:
          - kind: "dns#managedZonePrivateVisibilityConfigNetwork"
            networkUrl: "https://www.googleapis.com/compute/v1/projects/<PROJECT_ID>/global/networks/<NETWORK_ID>"
