# Example of the DNS managed zone template usage.
#
# In this example, a private DNS managed zone is created with the use of
# the `visibility` and `privateVisibilityConfig` properties.
#   <FIXME:project_id>: a valid project name.
#   <FIXME:network_id>: a valid VPC network name.

imports:
  - path: templates/dns_managed_zone/dns_managed_zone.py
    name: dns_managed_zone.py

resources:
  - name: private-mz-with-visibility
    type: dns_managed_zone.py
    properties:
      name: private-mz-with-visibility
      dnsName: private-visibility.local.
      description: "Private DNS Managed Zone with visibility config"
      visibility: private
      privateVisibilityConfig:
        kind: "dns#managedZonePrivateVisibilityConfig"
        networks:
          - kind: "dns#managedZonePrivateVisibilityConfigNetwork"
            networkUrl: "https://www.googleapis.com/compute/v1/projects/<FIXME:project_id>/global/networks/<FIXME:network_id>"
